version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/sockista

hooks:
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
