version: 0.2
phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
      - echo "Building the application..."
      - # You can add build commands here if needed
artifacts:
  files:
    - '**/*' # This means package all files in the directory